name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Inicializar buildozer
      run: buildozer init

    - name: Compilar APK
      run: buildozer android debug

    - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: VisitaTecnica-APK
        path: bin/*.apk
