name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies (incluindo git)
      run: |
        sudo apt-get update
        sudo apt-get install -y git openjdk-11-jdk wget unzip

    - name: Check git version
      run: git --version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Clean Buildozer cache
      run: |
        rm -rf ~/.buildozer
        rm -rf ./.buildozer

    - name: Update git submodules (se houver)
      run: git submodule update --init --recursive || echo "No submodules found"

    - name: Install Android SDK Command Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROID_HOME: ${{ env.HOME }}/android-sdk
        PATH: ${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin:${{ env.HOME }}/android-sdk/platform-tools:${{ env.PATH }}
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: VisitaTecnica-APK
        path: bin/*.apk
